version: 0.0.{build}
branches:
  only:
  - master
os:
  - Visual Studio 2015
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
configuration: Release
before_build: 
  - nuget restore AnotherJiraRestClient.sln
after_build:
  - nuget pack AnotherJiraRestClient\AnotherJiraRestClient.nuspec -Version %appveyor_build_version%
  - appveyor PushArtifact AnotherJiraRestClient-Ruskin.%appveyor_build_version%.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: dwlwOZs2kUAq1SshxnIJIwQPm3h2kcA8KBXKQsVje3/9l1yvJ3aBXmCXh0HP5ZDo
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/